version: '3'
services:
  docker:
    container_name: docker
    image: registry:2.8.3
    restart: always
    environment:
      - HTTP_PROXY=${PROXY}
      - HTTPS_PROXY=${PROXY}
    volumes:
      - ./docker/data:/var/lib/registry
      - ./docker/config.yml:/etc/docker/registry/config.yml
  nvcr:
    container_name: nvcr
    image: registry:2.8.3
    restart: always
    environment:
      - HTTP_PROXY=${PROXY}
      - HTTPS_PROXY=${PROXY}
    volumes:
      - ./nvcr/data:/var/lib/registry
      - ./nvcr/config.yml:/etc/docker/registry/config.yml
  gcr:
    container_name: gcr
    image: registry:2.8.3
    restart: always
    environment:
      - HTTP_PROXY=${PROXY}
      - HTTPS_PROXY=${PROXY}
    volumes:
      - ./gcr/data:/var/lib/registry
      - ./gcr/config.yml:/etc/docker/registry/config.yml
  ghcr:
    container_name: ghcr
    image: registry:2.8.3
    restart: always
    environment:
      - HTTP_PROXY=${PROXY}
      - HTTPS_PROXY=${PROXY}
    volumes:
      - ./ghcr/data:/var/lib/registry
      - ./ghcr/config.yml:/etc/docker/registry/config.yml
  k8s:
    container_name: k8s
    image: registry:2.8.3
    restart: always
    environment:
      - HTTP_PROXY=${PROXY}
      - HTTPS_PROXY=${PROXY}
    volumes:
      - ./k8s/data:/var/lib/registry
      - ./k8s/config.yml:/etc/docker/registry/config.yml
  quay:
    container_name: quay
    image: registry:2.8.3
    restart: always
    environment:
      - HTTP_PROXY=${PROXY}
      - HTTPS_PROXY=${PROXY}
    volumes:
      - ./quay/data:/var/lib/registry
      - ./quay/config.yml:/etc/docker/registry/config.yml
  nginx:
    container_name: nginx
    image: nginx:1.25.0
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
